"""Drop unused monolithic tables

Revision ID: 55909cb5b6c3
Revises: d7a15e45750f
Create Date: 2026-06-18 14:33:56.424545

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55909cb5b6c3"
down_revision: str | Sequence[str] | None = "d7a15e45750f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("CartItem")
    op.drop_table("PriceHistory")
    op.drop_table("ProductPrice")
    op.drop_table("Cart")
    op.drop_table("Product")
    op.drop_table("Category")
    op.drop_table("Retailer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Cart",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_cart_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Cart_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("cart_user_id_unique"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "ProductPrice",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("retailer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
        sa.Column(
            "discount_price", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True
        ),
        sa.Column("in_stock", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["Product.id"], name=op.f("ProductPrice_product_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"], ["Retailer.id"], name=op.f("ProductPrice_retailer_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ProductPrice_pkey")),
    )
    op.create_table(
        "CartItem",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("cart_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cart_id"], ["Cart.id"], name=op.f("CartItem_cart_id_fkey")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["Product.id"], name=op.f("CartItem_product_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("CartItem_pkey")),
    )
    op.create_table(
        "Retailer",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("logo_url", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("Retailer_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("retailer_name_unique"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "Category",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("Category_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("category_name_unique"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "slug",
            name=op.f("category_slug_unique"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "PriceHistory",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("retailer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
        sa.Column(
            "recorded_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["Product.id"], name=op.f("PriceHistory_product_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"], ["Retailer.id"], name=op.f("PriceHistory_retailer_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("PriceHistory_pkey")),
    )
    op.create_table(
        "Product",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("external_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "general_description", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "specifications",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["Category.id"], name=op.f("Product_category_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Product_pkey")),
    )
    # ### end Alembic commands ###
