"""add_telegram_id_to_user

Revision ID: 92e472ddc4dd
Revises: a1b2c3d4e5f6
Create Date: 2026-07-08 15:20:52.222367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e472ddc4dd'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_User_telegram_id'), 'User', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_telegram_id'), table_name='User')
    op.drop_column('User', 'telegram_id')
    # ### end Alembic commands ###
